sudo: false
language: python
matrix:
  include:
    - python: '2.7'
      env: TOXENV=py27-dj111
    - python: '3.4'
      env: TOXENV=py34-dj111
    - python: '3.4'
      env: TOXENV=py34-dj20
    - python: '3.5'
      env: TOXENV=py35-dj111
    - python: '3.5'
      env: TOXENV=py35-dj20
    - python: '3.5'
      env: TOXENV=py35-dj21
    - python: '3.6'
      env: TOXENV=py36-dj111
    - python: '3.6'
      env: TOXENV=py36-dj20
    - python: '3.6'
      env: TOXENV=py36-dj21
    - python: '3.7-dev'
      env: TOXENV=py37-dj20
    - python: '3.7-dev'
      env: TOXENV=py37-dj21
    - python: '3.7-dev'
      env: TOXENV=flake8
    - python: '3.7-dev'
      env: TOXENV=coverage
script:
  - tox
install:
  - pip install tox
