# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='M2M_ChildModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spam', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='M2M_ParentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bacon', models.ManyToManyField(to='django_app.M2M_ChildModel')),
            ],
        ),
        migrations.CreateModel(
            name='M2M_Through_ChildModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spam', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='M2M_Through_ParentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='M2M_ThroughModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knight', models.CharField(max_length=30)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_app.M2M_Through_ChildModel')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_app.M2M_Through_ParentModel')),
            ],
        ),
        migrations.AddField(
            model_name='m2m_through_parentmodel',
            name='bacon',
            field=models.ManyToManyField(through='django_app.M2M_ThroughModel', to='django_app.M2M_Through_ChildModel'),
        ),
    ]
